name: Build Signed Android APK

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-platform: '35'
        sdk-build-tools: '35.0.0'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Cache npm dependencies
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Install dependencies
      run: npm ci
      
    - name: Generate Keystore
      run: |
        keytool -genkeypair -v -storetype PKCS12 -keystore android/app/release.keystore -alias dongetive-key -keyalg RSA -keysize 2048 -validity 10000 -storepass dongetive123 -keypass dongetive123 -dname "CN=Dongetive, OU=Development, O=Dongetive, L=City, S=State, C=US"
      
    - name: Make Gradlew executable
      run: chmod +x android/gradlew
      
    - name: Build Signed APK
      run: |
        cd android
        ./gradlew assembleRelease -PMYAPP_UPLOAD_STORE_FILE=app/release.keystore -PMYAPP_UPLOAD_KEY_ALIAS=dongetive-key -PMYAPP_UPLOAD_STORE_PASSWORD=dongetive123 -PMYAPP_UPLOAD_KEY_PASSWORD=dongetive123
      env:
        ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
        
    - name: Upload Signed APK
      uses: actions/upload-artifact@v4
      with:
        name: dongetive-signed-release
        path: android/app/build/outputs/apk/release/app-release.apk
        retention-days: 30
        
    - name: Upload Keystore
      uses: actions/upload-artifact@v4
      with:
        name: release-keystore
        path: android/app/release.keystore
        retention-days: 30
        
    - name: Upload build info
      uses: actions/upload-artifact@v4
      with:
        name: build-info
        path: |
          android/app/build/outputs/
          android/build/
        retention-days: 7 